---
title: "Collaborative Filtering Algorithms"
author: "Jing Zhao (jz2786)"
date: "11/19/2017"
output: pdf_document
---

## Load Data
```{r}
movie_train <- read.csv("../data/data_sample/eachmovie_sample/data_train.csv")
movie_test <- read.csv("../data/data_sample/eachmovie_sample/data_test.csv")


MS_train <- read.csv("../data/data_sample/MS_sample/data_train.csv")
MS_test <- read.csv("../data/data_sample/MS_sample/data_train.csv")

```

## Convert raw movie data
```{r}
Transformer <- function(data.set){
  columns.data <- sort(unique(data.set$Movie))
  rows.data <- sort(unique(data.set$User))
  Table_ <- matrix(NA,nrow = length(rows.data), ncol = length(columns.data))
  for(i in 1:length(columns.data)){
    col.name <- columns.data[i]
    index <- which(data.set$Movie == col.name)
    scores <- data.set[index,4] #Scores
    users <- data.set[index,3] #Users
    index2 <- which(rows.data %in% users)
    Table_[index2,i] = scores
    Table_[!index2,i] = NA
    }
  colnames(Table_) <- columns.data
  rownames(Table_) <- rows.data
  return(Table_)
}
movie_train <- Transformer(movie_train)
movie_test <- Transformer(movie_test)
save(movie_train, file = "../output/movie_train.RData")
save(movie_test, file = "../output/movie_test.RData")
```

## Convert raw MS data

```{r}
Transformer2 <- function(data){
  user_num <- which(data$V1 == 'C')
  user_id <- data$V2[user_num]
  page_id <- unique(data$V2[which(data$V1 == 'V')])
  Table_2 <- matrix(0, nrow=length(user_id), ncol=length(page_id))
  rownames(Table_2) <- as.character(user_id)
  colnames(Table_2) <- as.character(page_id)
  for (i in 1:length(user_num)){
    start_num <- user_num[i]
    if (i != length(user_num)){
        end_num <- user_num[i+1]
    }
    else {
      end_num <- nrow(data)+1
    }
    
    user_id_mat <- as.character(user_id[i])
  
    for (j in (start_num+1):(end_num-1)){
      page_id_mat <- as.character(data$V2[j])
      Table_2[user_id_mat, page_id_mat] <- 1
    }
  }
  return(Table_2)
}
MS_train <- Transformer2(MS_train)
MS_test <- Transformer2(MS_test)
save(MS_train, file = "../output/MS_train.RData")
save(MS_test, file = "../output/MS_test.RData")

```

## Similarity Weight
```{r}
######## function to calculate similarity weight ##########
cal_weight <- function(data,method){
  ## calculate similarity weight
  ## input: data - movie data or MS data in wide form
  ##        method - 'pearson' or 'spaerman' or 'vector'
  ## output: similarity weight matrix
  library(lsa)
  data <- as.matrix(data)
  weight_mat <- matrix(NA,nrow=nrow(data),ncol=nrow(data))
  for(i in 1:nrow(data)){
    
    #index <- t(apply(data,1,function(x){return((!is.na(x))&(!is.na(data[i,])))}))
    weight_mat[i,] <- apply(data,1,function(x){
      index <- (!is.na(x))&(!is.na(data[i,]))
      if(sum(index)==0){
        return(0)
      }else{
        if(method == 'pearson'){
          return(cor(data[i,index],x[index],method='pearson'))
        }else if(method == 'spearman'){
          return(cor(data[i,index],x[index],method='spearman'))
        }else if(method == 'vector'){
          return(cosine(data[i,index],x[index]))
        }
      }
      
      
    })
    
  }
  return(round(weight_mat,4))
}

# pearson_weight <- cal_weight(movie_train,'pearson')
# spearman_weight <- cal_weight(movie_train,'spearman')
# vector_weight <- cal_weight(movie_train,'vector')
# 
# save(pearson_weight,file = './pearson_weight.RData')
# save(spearman_weight,file='./spearman_weight.RData')
# save(vector_weight,file = './vector_weight.RData')
# 
# 
# pearson_weight_MS <- cal_weight(MS_train,'pearson')
# spearman_weight_MS <- cal_weight(MS_train,'spearman')
# vector_weight_MS <- cal_weight(MS_train,'vector')
# 
# save(pearson_weight_MS,file = './pearson_weight_MS.RData')
# save(spearman_weight_MS,file='./spearman_weight_MS.RData')
# save(vector_weight_MS,file = './vector_weight_MS.RData')

```



## Significance Weighting
```{r}

significance_weight_assign <- function(i, j, mat=movie_train, not_rate = 0 ){
  r_i <- mat[i, ]
  r_j <- mat[j, ]
  n <- length(intersect(which(r_i != 0), which(r_j != 0)))
  if (n >= 50){
    return(1)
  }
  else {
    return(n/50)
  }
}

significance_weight_matrix <- function(mat_dim_1, mat = movie_train){
  mat_weight = matrix(1, nrow=mat_dim_1, ncol=mat_dim_1)
  for (i in 1:(mat_dim_1-1)){
    for (j in (i+1):mat_dim_1){
      weight <- significance_weight_assign(i, j, mat=mat)
      mat_weight[i, j] <- weight
      mat_weight[j, i] <- weight
    }
    
  }
  return(mat_weight)
}

#mat_significance_weight <- significance_weight_matrix(dim(movie_train)[1], mat = movie_train)
#save(mat_significance_weight, file = "significance_weight.RData")

#mat_significance_weight <- significance_weight_matrix(dim(MS_train)[1], mat = MS_train)
#save(mat_significance_weight, file = "significance_weight2.RData")


```

## Variance Weighting

```{r}
find_var <- function(mat=movie_train){
  var_vector <- apply(movie_train, 2, var)
  var_max <- max(var_vector)
  var_min <- min(var_vector)
  v <- (var_vector - var_min)/var_max
  return(v)
}

variance_weight_assign <- function(i, j, v, mat=movie_train){
  r_i <- scale(mat[i, ])
  r_j <- scale(mat[j, ])
  weight <- sum(v*r_i*r_j)/sum(v)
  return(weight)
}

variance_weight_matrix <- function(mat_dim_1, mat = movie_train){
  mat_weight = matrix(1, nrow=mat_dim_1, ncol=mat_dim_1)
  v <- find_var(mat = mat)
  for (i in 1:(mat_dim_1-1)){
    print(i)
    print(Sys.time())
    for (j in (i+1):mat_dim_1){
      weight <- variance_weight_assign(i, j, v, mat = movie_train)
      mat_weight[i, j] <- weight
      mat_weight[j, i] <- weight
    }
  }
  return(mat_weight)
}

#mat_variance_weight <- variance_weight_matrix(dim(movie_train)[1], mat = movie_train)
#save(mat_variance_weight, file = "variance_weight.RData")

#mat_variance_weight <- variance_weight_matrix(dim(MS_train)[1], mat = MS_train)
#save(mat_variance_weight, file = "variance_weight2.RData")

```



## Selecting Neighborhoods - correlation_thresholding
```{r}
thresholding = 0.1
subset.neighbor = floor(thresholding * nrow(try1))
top.neighbors = matrix(0, ncol = subset.neighbor, nrow = nrow(try1))
for(i in 1:nrow(try1)){
  vec1 = try1[i,]
  n = length(vec1)
  index_ = which(vec1 %in% sort(vec1,partial=n-1)[(n-1):(n - subset.neighbor)])
  top.neighbors[i,] = index_[1:subset.neighbor]
}
```

#Prediction
```{r}
#User: index of this user
#try: weights Table
rating.pred <- function(data.set, user, item, try, top.neighbors){
  avg.rating = mean(data.set[user,])
  neighbor.index = top.neighbors[user,]
  neighbor.weights = try[user,neighbor.index]
  neighbor.ratings = data.set[neighbor.index, item]
  neighbor.avg = mean(data.set[neighbor.index, ])
  pred =avg.rating +  sum((neighbor.ratings-neighbor.avg) * neighbor.weights)/sum(neighbor.weights)
  return(pred)
}
```


## Evaluation - ROC

```{r}
evaluation.roc <- function(roc_value, mat, mat.true){
  mat.criterion <- matrix(roc_value, nrow = nrow(mat), ncol = ncol(mat))
  same_num <- sum((mat >= mat.criterion) == (mat.true >= mat.criterion))
  n <- sum(mat != matrix(0, nrow=nrow(mat), ncol=ncol(mat)))
  return(same_num/n)
}
```

## Evaluation - MAE
```{r}
evaluation.mae <- function(pred.val, true.val){
  mae <- sum(abs(pred.val - true.val))/nrow(pred.val)
  return(mae)
}
```

## Evaluation - Rank Score
```{r}
rank_score <- function(predicted_test,true_test){
  ## function to calculate rank score of predicted value
  ## input: predicted_test - predicted value matrix of test data
  ##        true_test - test data matrix
  ## output: rank score
  predicted_test[is.na(predicted_test)] <- 0
  true_test[is.na(true_test)] <- 0
  
  rank_mat <- ncol(true_test)+1-t(apply(true_test,1,function(x){return(rank(x,ties.method = 'first'))}))
  
  #R_a_denominator <- 1/(2^((rank_mat-1)/4))
  #R_a_nominator <- max(predicted_test-apply(predicted_test,1,mean))
                    
  R_a <- apply(1/(2^((rank_mat-1)/4)) * predicted_test,1,sum)
  R_a_max <- apply(1/(2^((rank_mat-1)/4)) * true_test,1,sum)
  R <- 100*sum(R_a)/sum(R_a_max)
  return(R)
  
}
```

